export * as StudentTable from './student'
export * as TeacherTable from './teacher'
export * as GroupTable from './group'
export * as CourseTable from './course'
export * as AttendanceTable from './attendance'
export * as CourseGroupTable from './course-group'
export * as CourseTeacherTable from './course-teacher'
export * as ResetPasswordSessionTable from './reset-password-session'